# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  #twitter
  twitter_consumer_key: kJ2AIKJx01YEfAM1s0hDzMtKU
  twitter_consumer_secret: e86vGidadoKFsqIZ16bMZ3PpIS5kEAMOkdH2bWWDRK8n4ThxGa
  #tumblr
  tumblr_consumer_key: tTcy1inmm4gcL1V1zzM98Ius4g3F4nrenuRWXwWLLX45TZdmsZ
  tumblr_consumer_secret: igsYY5bgj0SvZOMpSztWwwNehOISgRFLbA2eKLs1HhAHODwaAr
  #instagram
  instagram_client_id: 0226b42a168743d7a4b82d27ba2f4616
  instagram_client_secret: 61953871c5b7422a9e890b83366a1977
  ##
  secret_key_base: 9c4c5071293f53ee47faf8bf76cc2cb9771ed03bea9551411edf17491b2cbc58837862f31916c7eacb965369a776a33f16d618ff2538b18574f7dde345abcabf

test:
  secret_key_base: 986813e04205e570d68b9ae4111a9a84550d3547600e7cb2f4831089d64d0fbc42052c260b6999593e7510900ac546bd66038aab5ae955c79e517bd5e044e466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
